import type { Metadata } from "next";
import "./globals.css";
import {
  ResizableHandle,
  ResizablePanel,
  ResizablePanelGroup,
} from "@/components/ui/resizable"
import Sidebar from "@/components/sidebar";
import { GenerationProvider } from '@/context/modalContext';

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className='min-w-screen min-h-screen w-screen h-screen font-geist'>

        <div className='w-full h-full font-geist rounded-xl bg-white'>

          {children}

        </div>

      </body>

    </html>
  );
}
